# Generated by Django 3.2.7 on 2021-09-18 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Продукт')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee', verbose_name='Продавец')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_one_item', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date_sale', models.DateField()),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employee', verbose_name='Продавец')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.item', verbose_name='Продукт')),
            ],
        ),
    ]
