# Generated by Django 3.2.7 on 2021-10-01 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_changeprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeprice',
            name='date_change',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 1, 14, 34, 1, 764652)),
        ),
    ]
