# Generated by Django 3.2.7 on 2021-10-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_changeprice_date_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeprice',
            name='date_change',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_sale',
            field=models.DateField(auto_created=True),
        ),
    ]
