# Generated by Django 3.2.7 on 2021-10-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20211005_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_sale',
            field=models.DateField(auto_now=True),
        ),
    ]
